### ISSUE TITLE
Typewriter mode

### ISSUE THREAD

**Issue by rugk** [UberWriter/uberwriter#61] opened 2018-06-12 16:51 UTC
A typewriter mode where you can only add text, but not edit would be nice. It's more a gimmick, but some say it helps to focus them.

Low prio, I'd say.

migrated from https://bugs.launchpad.net/uberwriter/+bug/1776291

**Comment by somas95** [comment] 2018-06-12 18:03
Duplicate of #40

**Closed by somas95** 2018-06-12 18:03 UTC
Labels: duplicate
