### ISSUE TITLE
[Git Master flatpak] Cannot find gtk/base.css

### ISSUE THREAD

**Issue by BrainBlasted** [UberWriter/uberwriter#149] opened 2019-04-22 19:32 UTC
### ENVIROMENT
- Linux distribution: Arch Linux
- Desktop Enviroment: GNOME
- DE version: 3.32
- GTK version: 3.24.X

### BUG

On the latest master when running from builder, I get the following error:
```
  File "/app/lib/python3.7/site-packages/uberwriter-2.2.0b1-py3.7.egg/uberwriter/application.py", line 150, in do_activate
    self.window = window.Window(self)
  File "/app/lib/python3.7/site-packages/uberwriter-2.2.0b1-py3.7.egg/uberwriter/window.py", line 163, in __init__
    self.apply_current_theme()
  File "/app/lib/python3.7/site-packages/uberwriter-2.2.0b1-py3.7.egg/uberwriter/window.py", line 179, in apply_current_theme
    style_provider.load_from_path(helpers.get_css_path("gtk/base.css"))
TypeError: Argument 1 does not allow None as a value
```

If we go back to before e87de14 it works fine.

Why not use gresource to bundle your data so you can use Gtk's file loading capabilities?

**Comment by goncalossilva** [comment] 2019-04-23 22:34
@somas95 Can you reproduce this?

> Why not use gresource to bundle your data so you can use Gtk's file loading capabilities?

This would be great, and I assume this is something @somas95 wanted to do at some point (it's in a comment right at the top of the file).

I have no experience with this: does it allow for custom CSS files to be supplied by users in the future?

**Comment by BrainBlasted** [comment] 2019-04-23 22:36
gresource does not, as it's a static format. A solution needs to be written for that separately if that's  a goal for the app.

**Comment by goncalossilva** [comment] 2019-04-23 22:48
This would be it: https://github.com/UberWriter/uberwriter/issues/123. I don't know what the plans are, though.

For the time being, I can't reproduce this particular issue, but I am not using builder. Looking at the change, it is likely related with using `folder/file.css` without going through `os.path.join`. I have a PR coming and will include a fix for this. :+1:

**Comment by BrainBlasted** [comment] 2019-04-23 22:50
Oh, did you mean choosing from bundled CSS, or actually adding new CSS?

**Comment by goncalossilva** [comment] 2019-04-23 23:19
Unsure, I don't know what the plans are, I'd suggest waiting for @somas95 :smile:

**Comment by somas95** [comment] 2019-04-24 06:19
A couple of quick comments (I'm on a trip and can't check properly anything not test it)

- Yes, I wanted to use gresources, at least for  .ui files. For .css ones I'm not so sure, as we may support custom styles in the future 

- I think that the issue here is with the setup.py file, not packaging the css files in the needed subfolders. I fixed that in another branch (the flatpak one, I think)

**Comment by BrainBlasted** [comment] 2019-04-24 20:55
You might be able to get the best of both worlds with DzlApplication: https://gitlab.gnome.org/GNOME/libdazzle/blob/master/src/app/dzl-application.c#L424

**Closed** 2019-11-02 18:44 UTC
