### ISSUE TITLE
xorg troubles on Elementary

### ISSUE THREAD

**Issue by thorbian** [UberWriter/uberwriter#91] opened 2018-11-26 11:00 UTC
![skaermbillede fra 2018-11-23 11-52-25](https://user-images.githubusercontent.com/26043747/49010196-c3e60e80-f172-11e8-9066-bc6f7b6c96f1.png)

### ENVIROMENT
- Linux distribution: Ubuntu lts
- Desktop Enviroment: Elementary
- DE version: Pantheon
- GTK version: pass

### BUG
Xorg use of cpu and fan skyrockets when I open uberwriter. It does not seem to react the same way when on xubuntu.

**Comment by somas95** [comment] 2018-11-26 13:11
Duplicate of #75

**Closed by somas95** 2018-11-26 13:11 UTC
