### ISSUE TITLE
UberWriter power consumption seems high

### ISSUE THREAD

**Issue by michel-slm** [UberWriter/uberwriter#75] opened 2018-08-21 00:31 UTC
### ENVIROMENT
- Linux distribution: Fedora 28
- Desktop Enviroment: GNOME on Xorg
- DE version: gnome-shell-3.28.3-1.fc28.x86_64
- GTK version: using Flatpak:
```
flatpak info org.gnome.Platform/x86_64/3.28
Ref: runtime/org.gnome.Platform/x86_64/3.28
ID: org.gnome.Platform
Arch: x86_64
Branch: 3.28
Origin: flathub
Active commit: cc7c2dd516160674998803e6ed6838091d628a3d25ff7465485ddecfb9f4363f
Latest commit: f5ad47d93872b617a6a05227d82e04481bc5a236c7299d04005e3c1f306f76d8
Parent: -
Location: /var/lib/flatpak/runtime/org.gnome.Platform/x86_64/3.28/cc7c2dd516160674998803e6ed6838091d628a3d25ff7465485ddecfb9f4363f
```

```
❯ flatpak info de.wolfvollprecht.UberWriter/x86_64/stable
Ref: app/de.wolfvollprecht.UberWriter/x86_64/stable
ID: de.wolfvollprecht.UberWriter
Arch: x86_64
Branch: stable
Origin: flathub
Collection ID: org.flathub.Stable
Date: 2018-07-27 18:08:26 +0000
Subject: v2.1.2 (4a6693ce)
Commit: 5f07056aad3ca18f717f05358cbf91cc4eaeb376a156a730fc83089fe4f9d6cf
Parent: c22b291a267f5176ee7876abc9de530f5ec3c8a12af20ba1b69d811377ede681
Location: /var/lib/flatpak/app/de.wolfvollprecht.UberWriter/x86_64/stable/5f07056aad3ca18f717f05358cbf91cc4eaeb376a156a730fc83089fe4f9d6cf
Installed size: 145.8 MB
Runtime: org.gnome.Platform/x86_64/3.28
Sdk: org.gnome.Sdk/x86_64/3.28
```

### BUG
With only GNOME Terminal running (with some tabs running mosh and Eternal Terminal sessions) my Thinkpad's power drain is around 6W:
![screenshot from 2018-08-20 17-20-28](https://user-images.githubusercontent.com/85603/44373538-9831f900-a49e-11e8-868a-7d03554f329d.png)

Firing up UberWriter, even idling (no file open) and with the window not overlapping the terminal window, the power drain jumps to at least 15W:
![screenshot from 2018-08-20 17-25-18](https://user-images.githubusercontent.com/85603/44373539-9831f900-a49e-11e8-8d62-c9e1bc617406.png)

Is UberWriter doing excessive polling?

**Comment by somas95** [comment] 2018-08-21 06:06
UberWriter polls mouse motion to show/hide the headerbar. That could be the
root of the issue, but this needs more debugging. If that is the issue a
two step mitigation could be done: disable the poller when the window is in
background (easy) and use another function (maybe some from gnome, it
surely exists) to poll the motion in an efficient way.
Anyway, this is purely speculation, I'll try to replicate the bug and find
the cause of it

**Comment by michel-slm** [comment] 2018-08-21 17:32
considering the power measurement I took was with the terminal in the foreground, even disabling the poller would definitely help a lot. But if GNOME can notify UberWriter when the mouse enters a given region that'd be even better

**Comment by wolfv** [comment] 2018-08-21 18:58
are you on wayland or Xorg?

I saw some issues on wayland with drawing the overlay gradient.

**Comment by michel-slm** [comment] 2018-08-23 16:59
@wolfv I'm on Fedora 28, but I'm running GNOME on Xorg

**Comment by somas95** [comment] 2018-08-23 17:05
On my system, I see these Uberwriter power consumptions:

Env | Iddle | Previewing images
-----|--------|------------------------
Xorg | 60 mW | 90 mW
Wayland |142 mW | 200 mW

While it's strange the bigger consumption on Wayland (a ~x2 factor), it could be related to what @wolfv pointed out. Any way, I can't see the almost 9 Watts of power consumption you see.

It's a consistent behaviour? Could you post the power est. powerto gives for the process? 
Thanks!

**Comment by somas95** [comment] 2018-08-23 17:13
Also, with no file open the consumption is anecdotic, for me at least:

Consumption | Usage | Events/s
-- | -- | --
786 μW | 9,3 μs/s | 0,05

**Comment by michel-slm** [comment] 2018-08-24 01:25
I suspect the increase in power usage is not only attributed only to UberWriter -- the HI_SOFTIRQ interrupt only shows up on powertop if UberWriter is running (likely due to the mouse polling).

How do I get the power estimate per app? I can only seem to find usage and events/s

**Comment by somas95** [comment] 2018-08-24 05:07
That's strange. Are you on a intel laptop? Powertop is designed by intel
for intel processors. For me, the column at the left shows power
consumption

**Comment by michel-slm** [comment] 2018-08-24 16:59
![screenshot from 2018-08-24 09-55-31](https://user-images.githubusercontent.com/85603/44597304-04a14680-a784-11e8-8c4b-649a093bc58b.png)

OK, I see the power consumption now. Probably just window size.

It's showing only 278 mW in this screenshot, but I noticed that the CPU utilization would spike to above 80% -- and would drop again once I close UberWriter

Looking at htop while UberWriter is running shows this is mostly Xorg

**Comment by somas95** [comment] 2018-08-24 19:34
I still can't replicate the issue. And by no means I have a powerful rig, in fact my laptop is on the low-end of the spectrum, so I really don't understand what's happening here.
Could you share your hardware specifications? 
Also, just for the sake of being sure that the installation is ok, could you try to uninstall and install uberwriter again?
Finally, do you have an hdd or a ssd?

**Comment by michel-slm** [comment] 2018-08-25 18:01
It's a brand new Thinkpad T480s: https://www.lenovo.com/us/en/laptops/thinkpad/thinkpad-t-series/ThinkPad-T480s/p/22TP2TT480S

512 GB SSD.

I'm beginning to suspect it's tied to the way UberWriter is packaged as a flatpak. I'll try these things:
- test on my less powerful Dell XPS13
- wipe the installation and all user data and reinstall
- try and build UberWriter myself and test on both

**Comment by somas95** [comment] 2018-10-11 09:06
@michel-slm hi, did you try those tests?

**Comment by cicindel** [comment] 2018-11-02 14:42
My laptop is also using lot of CPU (~50 %) when I have UberWriter open. Ubuntu 18.04 64bit, GNOME 3.28, flathub build. Dell Latitude 6430u with i5 CPU.

**Comment by somas95** [comment] 2018-11-26 13:14
I'll push finally a new version to flathub, now that one issue that prevented me to do it is solved. Let's see if the new manifest solves all this issues. If not, we'll see if it's the gradient the cause of the issues

**Comment by somas95** [comment] 2018-12-05 08:01
@michel-slm, @janxkoci There is a new version available at Flathub (2.1.3). Could you try it to see if it solves the high power consumption issue?

**Comment by janxkoci** [comment] 2018-12-05 09:32
I tried it yesterday, Xorg and UW still used CPU more than I would expect, but I didn't have enough time to try more stuff. I'll give it a go today.

**Comment by somas95** [comment] 2018-12-05 09:50
Hum. If you confirm this we'll need to try to disable the gradient that is drawn at the top and bottom of the window. I'll put a gschema setting to toggle it in next release. It would be nice to have a betta chanel on Flathub, but we don't have it. I could try to build a flatpak build so you can try to test this if you are willing to do it though

**Comment by janxkoci** [comment] 2018-12-05 14:36
So the CPU usage when using UW is now around 25 %, with occasional spikes. Most of it seems to be Xorg, which gnome-system-monitor reports to be using ~20 %. After closing UW, Xorg immediately drops to ~2 %.

**Comment by somas95** [comment] 2018-12-05 15:10
Maybe, I'm not sure. I could make a build with another namespace, if you want a paralel installation. Let me investigate this, let's see if we can pinpoint the issue (if only I could replicate it... but it only happens to some users)

**Comment by janxkoci** [comment] 2018-12-05 15:31
I don't think you have to bother with changing namespace, I can try your build and maybe it will work better :) Or I can later reinstall or something, no problem. In any case I have a second laptop with eOS + Quilter.

**Comment by janxkoci** [comment] 2018-12-06 12:13
Btw what gradient are you talking about? I don't see any gradient in the window unless the text is longer than the window size and it goes off - is that what you mean? Is it drawn even with text shorter than window size (so it doesn't go off)? Because I use it now to write short abstract, so it fits whole in the window.

**Comment by somas95** [comment] 2018-12-06 12:40
Yeah, I'm talking about that gradient. I'm putting two hidden settings to disable that gradient and the polling we make of the cursor to fade the headerbar. I'll push it to flathub likely today, so stay tuned

**Comment by somas95** [comment] 2018-12-06 14:50
2.1.4 is now on Flathub. 
Probably you'll need to install the gschemas file... Just grab it from [here](https://raw.githubusercontent.com/UberWriter/uberwriter/master/data/de.wolfvollprecht.UberWriter.gschema.xml) and copy it to `/usr/share/glib-2.0/schemas/`, and then run `sudo glib-compile-schemas /usr/share/glib-2.0/schemas`
Then you can toggle the gradient and the polling from dconf (just search "uberwriter" there)

**Comment by janxkoci** [comment] 2018-12-17 09:38
Hi, sorry for the delay, I was away with second laptop so I couldn't test it.

Now I compiled the schema and installed dconf but searching "uberwriter" gives no results in it. Do flatpak apps even appear there? Or do I need reboot or something?

**Comment by somas95** [comment] 2018-12-17 10:53
I'm really not sure. But if you compile it well it should appear there nomatter what. Are you sure you are searching with dconf, and not gconf? 


Remember you have to copy the schema to /usr/share/glib-2.0/schemas and then compile it with glib-compile-schemas 


Maybe in other systems that path is different? 


In any case, I'm exposing that option in the preferences window in the next version, but IDK when I will be able to ship it 




What I found is that we call a cairo function every time a draw signal I sent, and those are sent a lot of times per second. For some systems this have 0 impact in performance, for others it's killer. I still don't know what the difference between those systems is ( some powerful systems have issues while humble ones don't have any) 




On Mon, Dec 17, 2018 at 10:38 AM +0100, "janxkoci" <notifications@github.com> wrote:












Hi, sorry for the delay, I was away with second laptop so I couldn't test it.


Now I compiled the schema and installed dconf but searching "uberwriter" gives no results in it. Do flatpak apps even appear there? Or do I need reboot or something?

**Comment by janxkoci** [comment] 2018-12-17 12:09
@somas95 see my edit, I found it, toggling gradient off helped

**Comment by somas95** [comment] 2018-12-17 13:14
Like, a lot, or only partially? Did you try to disable mouse polling? (it shouldn't change anything, but we loss nothing trying)




On Mon, Dec 17, 2018 at 1:09 PM +0100, "janxkoci" <notifications@github.com> wrote:












@somas95 see my edit, I found it, toggling gradient off helped

**Comment by wolfv** [comment] 2018-12-17 16:21
I also think that the gradient is the main contributor to these issues, and testing out the dev build has fixed it for me :)

**Comment by fbruetting** [comment] 2019-02-21 13:42
Xorg and UberWriter together always consume one full core of my i7 machine, thats very excessive. I can see that even the menu opens very slow in comparison to every other program. Can you please fix that? UberWriter is totally unusable as long as this is not fixed.

I’m on Fedora 29, running Xorg and UberWriter-Flatpak.

**Comment by somas95** [comment] 2019-02-21 18:45
Hi, @fbruetting. Did you try this? I'll push as soon as I can the fix good schemas to flathub, and I'll disable the gradient by default, but in the meanwhile this could fix the issue for you 
 
> 2.1.4 is now on Flathub.
> Probably you'll need to install the gschemas file... Just grab it from [here](https://raw.githubusercontent.com/UberWriter/uberwriter/master/data/de.wolfvollprecht.UberWriter.gschema.xml) and copy it to `/usr/share/glib-2.0/schemas/`, and then run `sudo glib-compile-schemas /usr/share/glib-2.0/schemas`
> Then you can toggle the gradient and the polling from dconf (just search "uberwriter" there)

**Comment by fbruetting** [comment] 2019-02-22 16:59
Ah, I’m on Fedora Silverblue with an OSTree install, what means that `/usr/` is read-only for me. But I’ll try this at work on monday, where I have a regular Fedora installation.

**Comment by fbruetting** [comment] 2019-04-04 11:58
So with 2.1.5 this is gone for me. 👌️

**Closed** 2019-04-04 19:22 UTC
