### ISSUE TITLE
No undo

### ISSUE THREAD

**Issue by alerque** [UberWriter/uberwriter#155] opened 2019-04-28 07:21 UTC
I used the app for about 15 seconds before running into my first reason not to use it. I was trying out features it had and immediately messed up something in the Markdown file I opened. No problem, <kbd>Ctrl</kbd><kbd>Z</kbd> ... no‽ Okay then surely there is a button or menu with undo  ... no‽

**Comment by somas95** [comment] 2019-04-29 18:05
I don't get it

Undo is implemented, and I can't reproduce the issues you are describing. 
A small set of steps to reproduce the bug would be helpful, as well as the system specs (did you install UberWriter from Flathub, from a repository, are you using GNOME, etc etc...)

**Comment by alerque** [comment] 2019-04-29 18:26
I compiled from the latest (at the time of writing) git HEAD version. I didn't see any sign of an undo feature. Where should I be looking?

No I am not running Gnome (bare Xorg + Awesome WM) but do have Gnome installed and enough session stuff running that most other apps are able run fine with no issues. Gedit, Nautilus, etc. run as expected.

**Comment by somas95** [comment] 2019-04-29 18:47
Great!
Last month we had (and still have) a lot of movement in some branches. Could you build from [the last tag](https://github.com/UberWriter/uberwriter/releases/tag/v2.1.5a) instead of building from HEAD?

**Comment by somas95** [comment] 2019-05-01 00:28
Closing this, feel free to reopen if the issue shows again

**Closed by somas95** 2019-05-01 00:28 UTC
